;; Data


(setq my/init-files (list user-init-file
                          (concat user-emacs-directory "bugs.el")
                          (concat user-emacs-directory "scratch.el")
                          (concat user-emacs-directory "sql-notebook.el")
                          "~/.stumpwm.d/init.lisp"
                          "~/personal/automotive.org"
                          "~/personal/bookmarks.org"
                          "~/personal/cad.org"
                          "~/personal/design-notes.org"
                          "~/personal/diary"
                          "~/personal/dogs.org"
                          "~/personal/food.org"
                          "~/personal/ideas.org"
                          "~/personal/journal.org"
                          "~/personal/main.org"
                          "~/personal/media-queue.org"
                          "~/personal/programming-notes.org"
                          "~/personal/projects.org"
                          "~/personal/promise.org"
                          "~/personal/rem.org"
                          "~/personal/rem-structured.org"
                          "~/personal/quotes.org"
                          "~/personal/archive/buy.org"
                          "~/personal/archive/people.org"
                          "~/personal/archive/projects.org"
                          "~/personal/automotive/subaru-outback-2008/Notes.org"
                          "~/personal/automotive/subaru-outback-2008/log.org"
                          "~/personal/exercise/exercises.org"
                          "~/personal/exercise/misc.org"
                          "~/personal/exercise/movement.org"
                          "~/personal/exercise/records.org"
                          "~/personal/exercise/routines.org"
                          "~/personal/linux/emacs.org"
                          "~/personal/linux/linux.org"
                          "~/personal/printing/printing.org"
                          "~/conf/sync.org"
                          "~/conf/awesome/rc.lua"
                          "~/conf/i3/config"
                          "~/conf/zsh/.zshrc"
                          "~/conf/freecad/user.cfg"
                          "~/work/wnmu/Todo.org"
                          "~/work/wnmu/huddle-notes.org"
                          "~/work/wnmu/projects.org"
                          "~/work/wnmu/records/creds.org"
                          "~/work/wnmu/records/qr-code.org"
                          "~/work/wnmu/refactor.org"))
